//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ponteverdeCore.Models.BusinessModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class pais
    {
        public pais()
        {
            this.cidade = new HashSet<cidade>();
        }
    
        public long id { get; set; }
        public string nome { get; set; }
    
        public virtual ICollection<cidade> cidade { get; set; }
    }
}
