-- MySQL Script generated by MySQL Workbench
-- 10/20/15 23:51:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ponteverde
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ponteverde` ;

-- -----------------------------------------------------
-- Schema ponteverde
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ponteverde` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `ponteverde` ;

-- -----------------------------------------------------
-- Table `ponteverde`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ponteverde`.`Usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ponteverde`.`Usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `tipo` ENUM('1', '2') NULL COMMENT '1 - Cliente\n2 - Loja',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `ponteverde`.`Usuario` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ponteverde`.`Pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ponteverde`.`Pais` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ponteverde`.`Pais` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ponteverde`.`Cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ponteverde`.`Cidade` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ponteverde`.`Cidade` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idPais` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_idPais_id`
    FOREIGN KEY (`idPais`)
    REFERENCES `ponteverde`.`Pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_idPais_id_idx` ON `ponteverde`.`Cidade` (`idPais` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ponteverde`.`Bairro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ponteverde`.`Bairro` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ponteverde`.`Bairro` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `idCidade` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_idCidade_id`
    FOREIGN KEY (`idCidade`)
    REFERENCES `ponteverde`.`Cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_idCidade_id_idx` ON `ponteverde`.`Bairro` (`idCidade` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ponteverde`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ponteverde`.`Cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ponteverde`.`Cliente` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `idUsername` BIGINT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `fotowall` TEXT NOT NULL,
  `fotoperfil` TEXT NOT NULL,
  `cep` VARCHAR(45) NULL,
  `logradouro` VARCHAR(100) NULL,
  `numero` VARCHAR(25) NULL,
  `lat` DECIMAL(11,8) NULL,
  `long` DECIMAL(11,8) NULL,
  `idBairro` BIGINT NOT NULL,
  `statusPublico` ENUM('1', '2') NOT NULL COMMENT '1 - Publico\n2 - Privado',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_idUsername`
    FOREIGN KEY (`idUsername`)
    REFERENCES `ponteverde`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idBairro_id`
    FOREIGN KEY (`idBairro`)
    REFERENCES `ponteverde`.`Bairro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_idUsername_idx` ON `ponteverde`.`Cliente` (`idUsername` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_idBairro_id_idx` ON `ponteverde`.`Cliente` (`idBairro` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ponteverde`.`Loja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ponteverde`.`Loja` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ponteverde`.`Loja` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `idUsername` BIGINT NOT NULL,
  `nome` VARCHAR(25) NOT NULL,
  `fotowall` TEXT NOT NULL,
  `fotoperfil` TEXT NOT NULL,
  `cep` VARCHAR(45) NULL,
  `logradouro` VARCHAR(100) NULL,
  `numero` VARCHAR(25) NULL,
  `lat` DECIMAL(11,8) NULL,
  `long` DECIMAL(11,8) NULL,
  `cnpj` INT(20) NULL,
  `idBairro` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_idUsernameLoja_id`
    FOREIGN KEY (`idUsername`)
    REFERENCES `ponteverde`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IdBairroLoja`
    FOREIGN KEY (`idBairro`)
    REFERENCES `ponteverde`.`Bairro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_idusernameloja_id_idx` ON `ponteverde`.`Loja` (`idUsername` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_IdBairroLoja_idx` ON `ponteverde`.`Loja` (`idBairro` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ponteverde`.`LojaFavorita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ponteverde`.`LojaFavorita` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ponteverde`.`LojaFavorita` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `idLoja` BIGINT NOT NULL,
  `idCliente` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_idCliente_id`
    FOREIGN KEY (`idCliente`)
    REFERENCES `ponteverde`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idLoja_id`
    FOREIGN KEY (`idLoja`)
    REFERENCES `ponteverde`.`Loja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_idCliente_id_idx` ON `ponteverde`.`LojaFavorita` (`idCliente` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_idLoja_id_idx` ON `ponteverde`.`LojaFavorita` (`idLoja` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ponteverde`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ponteverde`.`Produto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ponteverde`.`Produto` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `preco` FLOAT(10,2) NOT NULL,
  `idLoja` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_idLojaProduto_id`
    FOREIGN KEY (`idLoja`)
    REFERENCES `ponteverde`.`Loja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_idLojaProduto_id_idx` ON `ponteverde`.`Produto` (`idLoja` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ponteverde`.`ProdutoFavorito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ponteverde`.`ProdutoFavorito` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ponteverde`.`ProdutoFavorito` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `idProduto` BIGINT NOT NULL,
  `idLojaFavorita` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ProdutoFavorito_LojaFavorita1`
    FOREIGN KEY (`idLojaFavorita`)
    REFERENCES `ponteverde`.`LojaFavorita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idProduto_id`
    FOREIGN KEY (`idProduto`)
    REFERENCES `ponteverde`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_ProdutoFavorito_LojaFavorita1_idx` ON `ponteverde`.`ProdutoFavorito` (`idLojaFavorita` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_idProduto_id_idx` ON `ponteverde`.`ProdutoFavorito` (`idProduto` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ponteverde`.`LojaFavorita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ponteverde`.`LojaFavorita` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ponteverde`.`LojaFavorita` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `idLoja` BIGINT NOT NULL,
  `idCliente` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_idCliente_id`
    FOREIGN KEY (`idCliente`)
    REFERENCES `ponteverde`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idLoja_id`
    FOREIGN KEY (`idLoja`)
    REFERENCES `ponteverde`.`Loja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ponteverde`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ponteverde`.`table1` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ponteverde`.`table1` (
)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ponteverde`.`Promocao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ponteverde`.`Promocao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ponteverde`.`Promocao` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `idProduto` BIGINT NOT NULL,
  `novopreco` FLOAT(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_idProduto_id`
    FOREIGN KEY (`idProduto`)
    REFERENCES `ponteverde`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_idProduto_id_idx` ON `ponteverde`.`Promocao` (`idProduto` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ponteverde`.`Servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ponteverde`.`Servico` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ponteverde`.`Servico` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(20) NULL,
  `descricao` VARCHAR(45) NULL,
  `idLoja` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Servico_Loja1`
    FOREIGN KEY (`idLoja`)
    REFERENCES `ponteverde`.`Loja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Servico_Loja1_idx` ON `ponteverde`.`Servico` (`idLoja` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ponteverde`.`Contato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ponteverde`.`Contato` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ponteverde`.`Contato` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `idUsuario` BIGINT NOT NULL,
  `telefone` INT(15) NULL,
  `celular` INT(15) NULL,
  `linkface` TEXT NULL,
  `linktwitter` TEXT NULL,
  `linkgplus` TEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_idLoja_id`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `ponteverde`.`Loja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_idLoja_id_idx` ON `ponteverde`.`Contato` (`idUsuario` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
