//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ponteverde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cidade
    {
        public cidade()
        {
            this.bairro = new HashSet<bairro>();
        }
    
        public long id { get; set; }
        public string nome { get; set; }
        public long idPais { get; set; }
    
        public virtual ICollection<bairro> bairro { get; set; }
        public virtual pais pais { get; set; }
    }
}
