//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ponteverde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public produto()
        {
            this.produtofavorito = new HashSet<produtofavorito>();
            this.promocao = new HashSet<promocao>();
        }
    
        public long id { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public float preco { get; set; }
        public long idLoja { get; set; }
        public long idCategoria { get; set; }
        public decimal prioridade { get; set; }
        public int dataCriacao { get; set; }
        public string linkfoto { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual loja loja { get; set; }
        public virtual ICollection<produtofavorito> produtofavorito { get; set; }
        public virtual ICollection<promocao> promocao { get; set; }
    }
}
