//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ponteverde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class promocao
    {
        public long id { get; set; }
        public float novopreco { get; set; }
        public long idProduto { get; set; }
    
        public virtual produto produto { get; set; }
    }
}
