//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ponteverde.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PvEntities : DbContext
    {
        public PvEntities()
            : base("name=PvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bairro> bairro { get; set; }
        public DbSet<categoria> categoria { get; set; }
        public DbSet<cidade> cidade { get; set; }
        public DbSet<cliente> cliente { get; set; }
        public DbSet<loja> loja { get; set; }
        public DbSet<lojafavorita> lojafavorita { get; set; }
        public DbSet<pais> pais { get; set; }
        public DbSet<produto> produto { get; set; }
        public DbSet<produtofavorito> produtofavorito { get; set; }
        public DbSet<promocao> promocao { get; set; }
        public DbSet<servico> servico { get; set; }
        public DbSet<usuario> usuario { get; set; }
    }
}
