//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ponteverde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.cliente = new HashSet<cliente>();
            this.loja = new HashSet<loja>();
        }
    
        public long id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string tipo { get; set; }
    
        public virtual ICollection<cliente> cliente { get; set; }
        public virtual ICollection<loja> loja { get; set; }
    }
}
